apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-monitor
  template:
    metadata:
      labels:
        app: traffic-monitor
    spec:
      containers:
      - name: monitor
        image: traffic-monitor:latest
        ports:
        - containerPort: 5000